<div id="dhl_psfinder_trigger">
    <a href="javascript:void(0);" onclick="addFirstEntry()">Test</a>
</div>
<script type="text/javascript">
    //<![CDATA[
    function addParcelFinderToShippingForm() {
        $('shipping-new-address-form').insert({
            top: $('dhl_psfinder_trigger')
        });
    }

    function addFirstEntry() {
        new Ajax.Request('<?php echo Mage::getBaseUrl(); ?>dhlpsf/facilities/', {
            parameters: $('co-billing-form').serialize(true),
            onSuccess: function (data) {
                var responseData = JSON.parse(data.responseText);

                // Check if stores was found
                if (responseData['success']) {
                    // Add Address of store in shipping form
                    var store = responseData['locations'][0];
                    $('shipping:street1').setValue(store['street'] + ' ' + store['houseNo']);
                    $('shipping:city').setValue(store['city']);
                    $('shipping:country_id').setValue(store['country']);
                    $('shipping:postcode').setValue(store['zipCode']);

                    alert('Adressdaten wurden übertragen');
                } else {
                    alert(responseData['message']);
                }
            }
        });
    }

    function addMapToCheckout() {
        this.insert({
            after: '<div id="map-canvas" style="height: 500px;"></div>'
        });

        <?php if(Mage::getSingleton('dhl_locationfinder/config')->getCurrentMapProvider()
    == Dhl_LocationFinder_Model_Adminhtml_System_Config_Source_Maptype::MAP_TYPE_GOOGLE): ?>
        var map = new google.maps.Map(
            document.getElementById('map-canvas'), // element
            {
                center: new google.maps.LatLng(52.4945047, 13.4006041),
                zoom: 7,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
        );

        // set map center based on a given address
        // see https://developers.google.com/maps/documentation/javascript/examples/geocoding-simple
        var geoCoder = new google.maps.Geocoder();
        geoCoder.geocode(
            {'address': 'Nonnenstraße, Leipzig'},
            function (results, status) {
                if (status === google.maps.GeocoderStatus.OK) {
                    map.setCenter(results[0].geometry.location);
                } else {
                    console.log('Geocode was not successful for the following reason: ' + status);
                }
            }
        );

        // TODO(nr): build data feed from webservice response
        var store = new storeLocator.Store(
            '387', // id
            new google.maps.LatLng(52.4945047, 13.4006041), // location
            null, // features
            { // info
                title: 'Post-Kaffee/Schreibwaren',
                address: 'Urbanstr. 183 Berlin 10961',
                phone: '',
                misc: 'psfTimeinfos?',
                web: '',
                street: 'Urbanstr.' // custom info from webservice response, see below
            }
        );
        var stores = [store];

        var dataFeed = new storeLocator.StaticDataFeed();
        dataFeed.setStores(stores);

        var view = new storeLocator.View(
            map,
            dataFeed,
            {
                geolocation: false
            }
        );

        stores.each(function (store) {
            view.getMarker(store).addListener("click", function () {
                console.log("TODO: write store info to form elements, e.g. " + this.getDetails().street);
            }.bind(store));
        });
        <?php endif; ?>
    }

    addParcelFinderToShippingForm();
    //]]>
</script>
